trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: 'mydockerhubuser/my-web-app'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'DockerHub7'
        tags: |
          $(Build.SourceBranchName)

- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: |
        npm install
        npm test
      displayName: 'Run Unit Tests'

- stage: Push
  dependsOn: Test
  jobs:
  - job: PushToDockerHub
    steps:
    - task: Docker@2
      inputs:
        command: push
        repository: 'anandjoy7/my-web-app'
        containerRegistry: 'DockerHub7'
        tags: |
          $(Build.SourceBranchName)

- stage: Deploy
  jobs:
  - job: DeployToAzure
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'AppConnection7'
        appName: 'my-web-app'
        imageName: 'anandjoy7/my-web-app:$(Build.SourceBranchName)'
