trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: 'anandjoy7/my-web-app'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.SourceBranchName)
        containerRegistry: 'DockerHub'  # Replace this with your service connection name

- stage: Test
  jobs:
  - job: RunTests
    steps:
    - script: |
        npm install
        npm test
      displayName: 'Run Unit Tests'

- stage: Push
  dependsOn: Test
  jobs:
  - job: PushToDockerHub
    steps:
    - task: Docker@2
      inputs:
        command: push
        repository: 'anandjoy7/my-web-app'
        tags: |
          $(Build.SourceBranchName)
        containerRegistry: 'DockerHub'  # Replace this with your service connection name

- stage: Deploy
  jobs:
  - job: DeployToAzure
    steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'AppConnection7'  # Replace with your Azure subscription name
              appName: 'my-web-app'  # Replace with your Azure Web App name
              imageName: 'anandjoy7/my-web-app:$(Build.SourceBranchName)'
